FROM golang:alpine AS builder

RUN apk add build-base npm
COPY . /src
RUN cd /src/cmd/WatchYourLAN/ && CGO_ENABLED=0 go build -o /WatchYourLAN .
RUN cd / && npm i bootswatch && npm i bootstrap-icons
    


FROM alpine

WORKDIR /app

RUN apk add --no-cache tzdata arp-scan \
    && mkdir /data

COPY --from=builder /WatchYourLAN /app/
COPY --from=builder /node_modules /app/

ENTRYPOINT ["./WatchYourLAN"]
CMD ["-b", "/app/node_modules"]