

function Donate() {

  return (
    <div class="card border-info">
      <div class="card-header">Donations and Work</div>
      <div class="card-body">
        <p>Every <a href="https://github.com/aceberg#donate" target="_blank">donation</a> is truly appreciated!</p>
        <p>I am offering self-hosted and mobile apps development for a small price.
          The Open Source apps I created are listed in my <a href="https://aceberg.github.io/portfolio/" target="_blank">portfolio</a>. They are all human-coded, not generated by AI. Please, <a href="https://github.com/aceberg#contact" target="_blank">contact</a> me, if you are interested.</p>
      </div>
    </div>
  )
}

export default Donate